### ISSUE TITLE
Cannot import bookmarks

### ISSUE THREAD

**Issue by HappyPeng2x** [HappyPeng2x/SumatoraDictionary#13]
Bookmark file shared from another app cannot be displayed or imported in version 0.4.5.2.
The reason is that the target SDK was bumped up to 30, but the manifest was not updated for the new permission scheme.
It will be solved in the next version hopefully released this week-end.

**Comment by Kohoshi12** [comment]
Hope the importing and exporting include the notes. They are very useful for me, I always write a phrase to them.

**Comment by HappyPeng2x** [comment]
Yes the importing and exporting include the notes.

Thanks again for your appreciation of this feature.
