### ISSUE TITLE
Screenshots for F-Droid 

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [HappyPeng2x/SumatoraDictionary#16]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by HappyPeng2x** [comment]
Yes I'd like to, and thank you for indicating the documentation to do it.

However at the moment my time is limited so I am focusing more on the code itself.
