### ISSUE TITLE
Bad input sanitization?

### ISSUE THREAD

**Issue by sG4ZvHrf** [HappyPeng2x/SumatoraDictionary#7]
### Expected Behavior
The application shouldn't crash.
### Actual Behavior
When searching for with `"` in any part of the query, the application crashes.
### How to Reproduce
Just search something like `"`, `"blah`, `blah"`, or `bl"ah`. `""` does not cause a crash.

**Comment by HappyPeng2x** [comment]
Thank you very much for the feedback.

Indeed it is required to sanitize input as MATCH queries for the FTS feature of SQLite are regex not plain text.
It is an oversight on my part and I will fix it for the next version.

**Comment by sG4ZvHrf** [comment]
I would also like to add that both `(` and `)` seems to crash the program. I tried other things like [SQLite's comment syntax](https://www.sqlite.org/lang_comment.html), semicolons, apostrophes, etc but those functioned just fine. So I presume the problem is more or less limited to parenthesis and quotes.

Not sure if this helps, but just mentioning it here in case it does.

**Comment by HappyPeng2x** [comment]
Yes it helped, and it is fixed in 0.4.5.2. Thanks again!
